version: '3.8'

services:
  cardzen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cardzen-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - cardzen_data:/app/data
    environment:
      - NODE_ENV=production

volumes:
  cardzen_data:
    driver: local
    # This ensures that the volume is created with proper permissions
    # The nextjs user has UID 1001 inside the container
